# Parameters
conn: 8  # {4, 8}
init_threshold: [20, 20, 20]
scale_fit_window: True
init_scale: 1.0
scale_list: [0.02, 0.05, 0.1, 0.2, 0.33, 0.5, 0.67, 1.0, 1.33, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0,
  11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0]
step_list: [0.01, 0.01, 0.01, 0.02, 0.02, 0.04, 0.04, 0.05, 0.05, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3,
            0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
window_size: [1920, 1080]

# Shortcuts
menu_Open_shortcut: 'Ctrl+O'
menu_Save_shortcut: 'Ctrl+S'
menu_Run_shortcut: 'F5'
menu_Undo_shortcut: 'Ctrl+Z'
menu_Delete_shortcut: 'Ctrl+D'
menu_Tutorial_shortcut: 'Ctrl+T'
